ASK_NAME = 'Как Вас зовут?'.freeze
ASK_GENDER = 'Укажите Ваш пол, введите М или Ж'.freeze
SKIP_STEP = 'Пропустить'.freeze
ADD_CARD = 'Добавить карту'.freeze
OPEN_CARDS = 'Открыть карты'.freeze
WIN = 'Вы победили'.freeze
LOSE = 'Вы проиграли'.freeze
DRAW = 'Ничья'.freeze
NEW_GAME = 'Хотите сыграть ещё?'.freeze
END_GAME = 'Закончить партию'.freeze
FAREWELL = 'Досвиданье!'.freeze
HIDDEN_CARD = "\u{1F0A0}".freeze
SORRY = "\u{1F641}".freeze
HAPPY = "\u{1F642}".freeze
ACES = ["\u{1F0A1}", "\u{1F0B1}", "\u{1F0C1}", "\u{1F0D1}"].freeze
NUMBERS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 'A', 'B', 'D', 'E'].freeze
SUITS = %w[A B C D].freeze
GENDERS = %w[М Ж].freeze
PREFIX = '1F0'.freeze
BOY = "\u{1F466}"
GIRL = "\u{1F467}"
GENDER = { М: BOY, Ж: GIRL }.freeze
